name: parking_app
description: "a Parking app made by students for their mini project in 2nd year of their studies"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
#--------PACKAGES-----#
dependencies:
  flutter:
    sdk: flutter
  #utility packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  get: ^4.6.6
#state management
get: ^4.6.5
get_storage: ^2.1.1
#product specific



#----------PACKAGES END--------#
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
#-------------LOCAL ASSETS----------#
    assets:
      - assets/logo/
      - assets/icons/
      - assets/images/
      - assets/images/onboarding.png
      - assets/images/verification.png


  #-------LOCAL FONTS----------#



  

